# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pages.github.dhl.com./nbd_lr/nbd_lr/"

git_url = "https://github.dhl.com/nbd_lr/nbd_lr/tree/master/"

def custom_doc_links(name): return None
