# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Stan']

# Cell
class Stan:
    def __init__(self):
        pass

    def predict(self, data):
        return "Class=B2B, confidence=98%"